### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by PankajJatav** [campudus/ff-node-opencv#1]
How did you resolve the Segmentation fault issue.

**Comment by Narigo** [comment]
Sorry, which Segmentation fault issue do you mean?

Here is the blog post where we described our journey leading to this repository:
https://campudus.github.io/en/blog/2015/06/08/face-recognition-with-nodejs-on-a-raspberry-pi/

**Comment by PankajJatav** [comment]
If I set 

if (counter < 100) {
    setTimeout(takePicture, 500);
  }
}

So how can I live streaming using openCV.

![selection_028](https://cloud.githubusercontent.com/assets/12525777/9494353/1969640e-4c23-11e5-856e-ded7c6e20824.png)

**Comment by Narigo** [comment]
@PankajJatav I guess you need to show more code than that. I didn't see segmentation faults while trying it out on my development machine...?

**Comment by PankajJatav** [comment]
## Here is Code.

var cv = require('opencv');
var counter = 0;
var camera;

try {
  camera = new cv.VideoCapture(0);

  setTimeout(takePicture, 500);
} catch (e) {
  console.log("Couldn't start camera:", e)
}

function takePicture() {
  camera.read(function (err, im) {
    if (err) throw err;
    console.log(im.size());
    if (im.size()[0] > 0 && im.size()[1] > 0) {
      im.detectObject("../data/haarcascade_frontalface_alt.xml", {}, function (err, faces) {
        if (err) throw err;

```
    if (faces.length > 0) {
      cv.readImage("./imgs/hideme.png", function (err, hideme) {
        if (err) throw err;

        for (var i = 0; i < faces.length; i++) {
          console.log('found a face');
          var face = faces[i];
          //var result = im.roi(face.x, face.y, face.width, face.height);
          //displayImage('image', im);
          //displayImage('mask', hideme);
          hideme.resize(face.width, face.height);
          var result = new cv.Matrix(hideme.width(), hideme.height());
          result.addWeighted(im.roi(face.x, face.y, face.width, face.height), 0.5, hideme, 1, 0.5);
          //var ims = hideme.size();
          //hideme.adjustROI(-face.y, (face.y + face.height) - ims[0], -face.x, (face.x + face.width) - ims[1]);
          //result.addWeighted(result, 1.0, resized, 1, 1.0);
          result.save('./imgs/hideme_' + counter + '.png');
          counter++;
          console.log('Image saved');
        }
      });
    }
  });
}
```

  });

  if (counter < 100) {
    setTimeout(takePicture, 500);
  }
}

**Comment by Narigo** [comment]
I tried that code right now and it worked for me (on my development machine, at least). There might be some hardware related problem for you? You might have more luck asking the opencv module maintainer...
